
app:
    name: ksnowlv关于Gin框架学习实践
    version: v1.0
    build: 101
    # poolsize: 150
    # host: localhost:6379
    # password: 1
    # db: 0

redis:
    host: localhost:6379
    password: 
    db: 0
    poolsize: 150
  
    

